spring:
  application:
    name: zzii-ai-code-mother-backend

server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.nylg.zziiaicodemother.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
