spring:
  # session 配置
  session:
    store-type: redis
    # session 1 天过期
    timeout: 86400
  datasource:
    url: jdbc:mysql://localhost:3306/zzii_ai_code_mother?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: zzii-ai-code-mother
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  profiles:
    active: local

# 用户头像上传目录
file:
  upload:
    avatar-dir: tmp/avatar

server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 1 天过期
    session:
      cookie:
        max-age: 86400

mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 将SQL输出到控制台[reference:3][reference:4]

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.nylg.zziiaicodemother.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
